### ISSUE TITLE
Bombable as an addon

### ISSUE THREAD

**Issue by slawekmikula** [bhugh/Bombable#14]
Hi. I can provide some help with converting bombable into addon architecture (https://wiki.flightgear.org/Addon). If there will be some kind of interest I can work on it in my spare time (very limited but anyway noone is working on it right now). This code could be encapsulated as an addon with easier path to install for other (not experienced) users.

**Comment by bhugh** [comment]
I just merged alexeijd's pull request, which converts this to add-on format, and hopefully resolves the issue.  But if you see further improvements/changes needed, feel free to submit them.

**Comment by slawekmikula** [comment]
Can be closed. We've discussed it elsewhere. By coincidence I've created this issue in the same time. Can this addon be mentioned on the wiki  https://wiki.flightgear.org/Addon ?

**Comment by slawekmikula** [comment]
Closing. Authors have managed to do it themselves.
